### ISSUE TITLE
What is pre-web-activate hook

### ISSUE THREAD

**Issue by esteinborn** [acquia/cloud-hooks#31]
Can you explain what this folder is and when it would fire?

Thanks.

**Comment by codwazny** [comment]
The folder is pre-web-activate

https://github.com/acquia/cloud-hooks/blob/496e13488a0e39637d28881af6e8e0460c4db2e2/README.md#pre-web-activate

**Comment by esteinborn** [comment]
Nice. Thanks for that. may want to merge that PR into the master branch readme :)

**Comment by codwazny** [comment]
Oh, I didn't even realize it wasn't merged. I'll check up on that.

**Comment by codwazny** [comment]
Now that I look at it. I think it was dropped because the comments for it weren't exactly accurate. While it does trigger the first time code is deployed to a server. There are other events which may change things such as the IP address of the server which will not reactivate the hook.

I'm not sure we actually publicly "support" the hook in its current existence due to some of those flaws. Sorry if I lead you astray.

We also have some upcoming features over the next year or so that will likely make this hook no longer possible to do. I would try not to use this hook.

**Comment by dripl** [comment]
I'm a bit confused by this "not sure we support" and "try not to use" statements. The hook is actually mentioned in current ACSF distro docs: https://docs.acquia.com/site-factory/workflow/distro.
Thanks for any advise.
